### ISSUE TITLE
Valid file with no tests raises a SyntaxError exception immediately after "Starting elm-doctest ..."

### ISSUE THREAD

**Issue by sdaves** [tshm/elm-doctest#9]
Using:

http://elm-lang.org/examples/random

    $ elm-doctest Random.elm
    Starting elm-doctest ...
    
    processing: /tmp/Random.elm
    undefined:1
    > > > > | | > 
    ^

    SyntaxError: Unexpected token > in JSON at position 0
        at Object.parse (native)
        at Array.app.ports.evaluate.subscribe.resource (/home/user/projects/trustedexpert/projects/brokedown-web/node_modules/elm-doctest/src/bridge.js:103:40)
        at Function.onEffects [as func] (/home/user/projects/trustedexpert/projects/brokedown-web/node_modules/elm-doctest/distribution/index.js:3456:12)
        at A3 (/home/user/projects/trustedexpert/projects/brokedown-web/node_modules/elm-doctest/distribution/index.js:98:11)
        at onMessage (/home/user/projects/trustedexpert/projects/brokedown-web/node_modules/elm-doctest/distribution/index.js:3241:12)
        at Object.callback (/home/user/projects/trustedexpert/projects/brokedown-web/node_modules/elm-doctest/distribution/index.js:3283:11)
        at step (/home/user/projects/trustedexpert/projects/brokedown-web/node_modules/elm-doctest/distribution/index.js:2921:32)
        at Timeout.work [as _onTimeout] (/home/user/projects/trustedexpert/projects/brokedown-web/node_modules/elm-doctest/distribution/index.js:2963:15)
        at tryOnTimeout (timers.js:232:11)
        at Timer.listOnTimeout (timers.js:202:5)

Looks like its having an issue parsing the JSON at [bridge.js line 103](https://github.com/tshm/elm-doctest/blob/master/src/bridge.js#L103).

**Comment by tshm** [comment]
right now, elm-doctest requires module declaration.
I'll try to address the issue by just adding the dummy line.

**Comment by sdaves** [comment]
Nice fix!

However, this example throws the same error:

```
module DoctestParamError exposing (Msg(Example))
type Msg = Example
```

I think it is failing on the open parentheses after Msg.

**Comment by tshm** [comment]
parser for module declaration fails for the case.  Reopening it.

**Comment by sdaves** [comment]
Thanks!
